/** Lista fixa exibida no select do formulario publico de agendamento. */
export const PROCEDIMENTOS = [
  'Consulta Dermatológica',
  'Blefaroplastia',
  'Lifting Facial',
  'Full Face / Harmonização Facial',
  'Ácido Hialurônico / Preenchimento',
  'Toxina Botulínica / Botox',
  'Bioestimulador de Colágeno',
  'Lip Lifting',
  'Castanhares',
  'Alectomia',
  'Lipo de Papada',
  'Protocolo Delta',
  'Face Hyden',
  'Cirurgia Dermatológica',
  'Pintas, Sinais e Lesões de Pele',
  'Câncer de Pele',
  'Acne',
  'Cicatrizes de Acne',
  'Melasma / Hiperpigmentação',
  'Dermatites e Alergias de Pele',
  'Psoríase',
  'Vitiligo',
  'Rosácea',
  'Consulta Dermatológica Infantil',
] as const
